[tool.poetry]
name = "ssh-zone-handler"
version = "0.1.1"
description = "SSH commands to provide Secondary DNS self-service."
readme = "README.md"
license = "MIT"
authors = ["Andreas Olsson <andreas@arrakis.se>"]
repository = "https://github.com/andreaso/ssh-zone-handler"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.3.0"
mypy = "^0.942"
pylint = "^2.13.7"
pytest = "^7.1.2"
pytest-mock = "^3.7.0"

[tool.poetry.scripts]
szh-sudoers = "ssh_zone_handler.cli:sudoers"
szh-wrapper = "ssh_zone_handler.cli:wrapper"

[tool.isort]
profile = "black"

[tool.pylint.'MASTER']
extension-pkg-allow-list = "pydantic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
