#!/bin/bash
set -o errexit
set -o nounset
set -o noglob
set -o pipefail

dynamic_path="$(dirname "$(realpath "$0")")/.dynamic"
mp_info_path="${dynamic_path}/multipass_info.json"
ssh_key_path="${dynamic_path}/id_alice_ed25519"

named_ip=$(jq -r '.info."szh-named".ipv4[0]' < "$mp_info_path")
knot_ip=$(jq -r '.info."szh-knot".ipv4[0]' < "$mp_info_path")

cat <<EOF
Host szh-named
     Hostname $named_ip

Host szh-knot
     Hostname $knot_ip

Host *
     User alice
     IdentitiesOnly yes
     IdentityFile $ssh_key_path
     UserKnownHostsFile $(mktemp -p /tmp szh-known-hosts-XXXXXXX)
     StrictHostKeyChecking no
EOF
