#!/bin/bash
set -o errexit
set -o nounset
set -o noglob
set -o pipefail

generated_path="$(dirname "$(realpath "$0")")/.generated"
mp_info_path="${generated_path}/multipass_info.json"
ssh_key_path="${generated_path}/id_alice_ed25519"

secondary_ip=$(jq -r '.info."szh-secondary".ipv4[0]' < "$mp_info_path")
tertiary_ip=$(jq -r '.info."szh-tertiary".ipv4[0]' < "$mp_info_path")

cat <<EOF
Host szh-secondary
     Hostname $secondary_ip

Host szh-tertiary
     Hostname $tertiary_ip

Host *
     User alice
     IdentitiesOnly yes
     IdentityFile $ssh_key_path
     UserKnownHostsFile $(mktemp -p /tmp szh-known-hosts-XXXXXXX)
     StrictHostKeyChecking no
EOF
