#!/usr/bin/env python3
# ruff: noqa: PLW1510, S101

import subprocess
import sys
from pathlib import Path
from typing import Final

from integration_cases import TestCase, cases


class RunTests:
    def __init__(self) -> None:
        self.ssh_conf_path: Final[Path] = (
            Path(__file__).parent.parent / "devel/.dynamic/ssh_conf"
        )

    def test(self, host: str, daemon: str, tc: TestCase) -> None:
        full_command = [
            "ssh",
            "-F",
            str(self.ssh_conf_path),
            "-l",
            "zones",
            host,
            tc.command,
        ]
        full_command += tc.zones

        chosen_stdout: str = tc.stdout.pick(daemon)
        chosen_stderr: str = tc.stderr.pick(daemon)

        result = subprocess.run(full_command, capture_output=True, text=True)

        try:
            assert result.returncode == tc.rc
        except AssertionError as error:
            print(f"Expected return code: {tc.rc}")
            print(f"Resulted return code: {result.returncode}")
            raise error
        try:
            assert result.stderr == chosen_stderr
        except AssertionError as error:
            print(f"Expected standard error:  {chosen_stderr!r}")
            print(f"Resulted standard error:  {result.stderr!r}")
            raise error
        try:
            assert result.stdout == chosen_stdout
        except AssertionError as error:
            print(f"Expected standard output:  {chosen_stdout!r}")
            print(f"Resulted standard output:  {result.stdout!r}")
            raise error


def main() -> None:
    rt = RunTests()

    try:
        daemon = sys.argv[1]
    except IndexError:
        print(f"Usage: {sys.argv[0]} DAEMON", file=sys.stderr)
        sys.exit(1)

    if daemon == "BIND9":
        host = "szh-named"
    elif daemon == "Knot":
        host = "szh-knot"
    else:
        raise ValueError("Unsupported daemon")

    print(f"* Testing {host} {daemon} host")
    tc: TestCase
    for tc in cases:
        print(f"** Test {tc.name}")
        try:
            rt.test(host, daemon, tc)
        except AssertionError:
            print(
                "\nTest failed. Aborting.",
            )
            sys.exit(1)


if __name__ == "__main__":
    main()
