---

name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  poetry:
    name: Poetry

    strategy:
      matrix:
        py_version: ["3.10", "3.11"]

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install Poetry
        run: pipx install poetry

      - name: Enable Python ${{ matrix.py_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py_version }}

      - name: Use Python ${{ matrix.py_version }} with Poetry
        run: poetry env use python${{ matrix.py_version }}

      - name: Install dependencies
        run: poetry install

      - name: Check import order
        run: poetry run isort --check ssh_zone_handler/ tests/

      - name: Check Black formating
        run: poetry run black --check ssh_zone_handler/ tests/

      - name: Verify type hints
        run: poetry run mypy --strict ssh_zone_handler/

      - name: Run Pylint
        run: poetry run pylint -rn -sn ssh_zone_handler/ tests/

      - name: Run Pytest
        run: poetry run pytest

  secondary:
    name: Secondary linting
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Secondary Linters
        uses: andreaso/setup-secondary-linters@main

      - name: Lint GitHub Actions workflows
        run: actionlint

      - name: Analyze GitHub Actions
        run: zizmor --format=github .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Markdown lint README
        run: markdownlint --disable MD012 MD013 MD014 MD040 -- README.md
