---

name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  poetry:
    name: Poetry
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check import order
        run: poetry run isort --check ssh_zone_handler/ tests/

      - name: Check Black formating
        run: poetry run black --check ssh_zone_handler/ tests/

      - name: Verify type hints
        run: poetry run mypy --strict ssh_zone_handler/

      - name: Run Pylint
        run: poetry run pylint -rn -sn ssh_zone_handler/ tests/

      - name: Run Bandit
        run: poetry run bandit -c pyproject.toml -r ssh_zone_handler/ tests/

      - name: Run Pytest
        run: poetry run pytest

  lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
